version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel
    ports:
      - "80:80"
    volumes:
      - ./www/:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - laravel
networks:
  laravel:
    driver: bridge